export const toolNames = [
  "readTasks",
  "createTasks",
  "updateTask",
  "updateTasksStatus",
  "updateTasksPriority",
  "deleteTask",
  "getCurrentTime",
  "readAreas",
  "createArea",
  "updateArea",
  "setAreaArchived",
  "deleteArea",
  "readProjects",
  "createProject",
  "updateProject",
  "setProjectArchived",
  "deleteProject",
  "readDocuments",
  "readDocument",
  "createDocument",
  "updateDocument",
  "deleteDocument",
] as const;
export type ToolName = (typeof toolNames)[number];
