export const toolNames = [
  "searchWeb",
  "scrapeWebpage",
  "readTasks",
  "createTasks",
  "updateTask",
  "updateTasksStatus",
  "updateTasksPriority",
  "assignTasksToMilestone",
  "deleteTask",
  "getCurrentTime",
  "readAreas",
  "createArea",
  "updateArea",
  "setAreaArchived",
  "deleteArea",
  "readProjects",
  "createProject",
  "updateProject",
  "setProjectArchived",
  "deleteProject",
  "readDocuments",
  "readDocument",
  "createDocument",
  "updateDocument",
  "deleteDocument",
  "readMilestones",
  "createMilestones",
  "updateMilestone",
  "updateMilestonesStatus",
  "moveMilestone",
  "deleteMilestone",
  "readActivity",
  "readUserProfile",
] as const;
export type ToolName = (typeof toolNames)[number];

export const toolApprovalMap: Record<ToolName, boolean> = {
  searchWeb: false,
  scrapeWebpage: false,
  readTasks: false,
  createTasks: true,
  updateTask: true,
  updateTasksStatus: true,
  updateTasksPriority: true,
  assignTasksToMilestone: true,
  deleteTask: true,
  getCurrentTime: false,
  readAreas: false,
  createArea: true,
  updateArea: true,
  setAreaArchived: true,
  deleteArea: true,
  readProjects: false,
  createProject: true,
  updateProject: true,
  setProjectArchived: true,
  deleteProject: true,
  readDocuments: false,
  readDocument: false,
  createDocument: true,
  updateDocument: true,
  deleteDocument: true,
  readMilestones: false,
  createMilestones: true,
  updateMilestone: true,
  updateMilestonesStatus: true,
  moveMilestone: true,
  deleteMilestone: true,
  readActivity: false,
  readUserProfile: false,
};
